### ISSUE TITLE
Keep downloads in one line

### ISSUE THREAD

**Issue by Komanc** [jwensley2/DownloadStatusBar#9] opened 2017-12-06 16:59 UTC
Not like this ![Image](https://user-images.githubusercontent.com/159303/33674007-a3636e54-daae-11e7-91d8-465bb0cd5c70.png)

Anyway, nice start!

**Comment by jwensley2** [comment] 2017-12-06 17:01
This will be in the next version.

Duplicate of #4.

**Closed by jwensley2** 2017-12-06 17:01 UTC

**Comment by jwensley2** [comment] 2017-12-07 06:48
There is a beta version now if you want to try this out.
https://addons.mozilla.org/en-US/firefox/addon/wx-download-status-bar/versions/beta?page=1#version-1.6.0beta1
