### ISSUE TITLE
FEATURE REQUEST - make bar able to "execute" the downloads

### ISSUE THREAD

**Issue by ibox99** [jwensley2/DownloadStatusBar#35] opened 2017-12-28 11:42 UTC
Sorry, i know this is the best place for this.

The Feature Request is so that we can execute the downloads directly, instead of having to open the folder and then execute.

Thanks for your work.

**Comment by Sopor-** [comment] 2017-12-28 14:21
already requested #14

**Comment by jwensley2** [comment] 2017-12-28 22:06
Duplicate of #14

**Closed by jwensley2** 2017-12-28 22:06 UTC
