### ISSUE TITLE
Open a downloaded file by double clicking on it

### ISSUE THREAD

**Issue by clairem59** [jwensley2/DownloadStatusBar#55] opened 2018-02-23 01:39 UTC
Hello,
Can you add this feature ?
When double clicking on a fully downloaded file, it should be opened.
Regards,
Claire

**Comment by jwensley2** [comment] 2018-02-23 04:47
Duplicate of #14

This isn't really possible right now, if it's made possible in the future I will add it.

**Closed by jwensley2** 2018-02-23 04:47 UTC
